### ISSUE TITLE
Feature Request: Text Wraparound

### ISSUE THREAD

**Issue by MrBelles** [Tectato/BetterCommandBlockUI#10]
By default, the mod uses the next lines if there are any brackets. I am suggesting it also go to the next line if the command is too long, and that it would cut off in the middle of words once it reaches the end of the window. I attached an example of how a text editor would handle the wrapping a command with brackets.
<img width="790" alt="Screenshot 2023-04-07 at 12 38 44 PM" src="https://user-images.githubusercontent.com/75463099/230667349-71f39b0c-218c-4f97-9512-d751ea2f945b.png">
<img width="423" alt="Screenshot 2023-04-07 at 12 38 56 PM" src="https://user-images.githubusercontent.com/75463099/230667354-cc327724-07b7-4742-9a70-7fe01c4a909f.png">

Here's an example of how it would look for a simpler command without brackets:
![Unwrapped](https://user-images.githubusercontent.com/75463099/230668195-58a38502-6249-45d6-bb6d-9444bf82fa5c.png)
![Wrapped](https://user-images.githubusercontent.com/75463099/230668197-441b8490-9ed4-4200-bbb3-6483d875f527.png)

**Comment by Tectato** [comment]
Sounds like a solid idea, I'll try to implement it like that as a configurable option

**Comment by MrBelles** [comment]
Sounds awesome. Thanks for the feedback!

**Comment by Tectato** [comment]
What should happen if the indentation from a lot of parentheses causes those to go off screen? Wrapping those back to the very left seems a bit jarring, what i could do instead would be to have a configurable wraparound width which starts at the current indentation. This would mean wrapped lines could still go off screen if they start off far to the right, but if you scroll over a bit you'd be able to see the whole line at once.
Also in the next update the window scrolls automatically if you move the cursor out of view, so scrolling will be even easier now.

**Comment by MrBelles** [comment]
I see, wrapping text to the very left that was indented would break it’s
format. Your proposal of having the configured wrap around sounds great,
and I can manage with the rare cases where the indenting is far to the
right. Thank you for the response!

**Comment by Tectato** [comment]
[dev build.zip](https://github.com/Tectato/BetterCommandBlockUI/files/11303544/dev.build.zip)
Here's a build for 1.19.4 if you want to test it already. I'll be backporting all the new stuff to the other versions and publishing it once I'm done

**Comment by Tectato** [comment]
Alright it's out for 1.18.2-1.19.4
