### ISSUE TITLE
Support for custom styles

### ISSUE THREAD

**Issue by OldWorldOrdr** [Tectato/BetterCommandBlockUI#13]
This mod is great but I don't like some of the ways line breaks are added, for example I prefer for closing braces to get their own line.

Mod behavior:
```
execute if entity @p
[
  distance=..2,
  gamemode=creative,
  tag=!sus
] run particle flame ~ ~1 ~ 0 0 0 .01 1
```

What I want
```
execute if entity @p
[
  distance=..2,
  gamemode=creative,
  tag=!sus
]
run particle flame ~ ~1 ~ 0 0 0 .01 1
```

It would be nice if people could make their own indentation style somehow, maybe an options menu where you can enable or disable different places for line breaks

**Comment by Tectato** [comment]
Added an implementation here: https://github.com/Tectato/BetterCommandBlockUI/issues/30
I hope this works for you

**Comment by OldWorldOrdr** [comment]
Haven't played Minecraft in a while and I don't feel like setting it up to test that, so I'll close the issue.
