### ISSUE TITLE
Crash on 1.20.1

### ISSUE THREAD

**Issue by iconsumeplutonium** [Tectato/BetterCommandBlockUI#14]
Minecraft version: 1.20.1
Fabric Version: 0.14.21
Mod Version: 0.4.2

Crash log 1: https://pastebin.com/Tg9zc6ML
If you go into any multiplayer server, and hit escape to bring up the Back to game/options/Quit to menu screen, the game will then crash.

Crash log 2: https://pastebin.com/sYYUWhwv
On the main menu, hit the button to go into the Singeplayer menu. The game will crash.

**Comment by Tectato** [comment]
I can't reproduce the crash in either situation, are you certain you're using the 1.20 version of the mod and not the 1.19.4 one?

**Comment by iconsumeplutonium** [comment]
Yep, turns out I was using the 1.19.4 verison of the mod. Got mixed up with the fact that both versions of the mod are called 0.4.2. Updated to the proper 1.20 version and it works now!
