### ISSUE TITLE
[FEATURE REQUEST] Scrollable Highlight

### ISSUE THREAD

**Issue by Coswics** [Tectato/BetterCommandBlockUI#18]
We Want to request the feature to click and select (scroll mouse over) text and select it

**Comment by Tectato** [comment]
Sounds reasonable, I'll try to add that in the next update. Until then, you can also click on one end of your selection and hold shift while clicking the other end to select the text inbetween those

**Comment by Tectato** [comment]
Implemented here: https://github.com/Tectato/BetterCommandBlockUI/issues/30
