### ISSUE TITLE
1.19.3 Bug: Game crashes when opening a Command Block

### ISSUE THREAD

**Issue by java-jambalaya** [Tectato/BetterCommandBlockUI#2]
- Minecraft: 1.19.3
- Fabric: 0.14.11

Reproduced by attempting to interact with a command block.

**Comment by Tectato** [comment]
The mod has been updated for 1.19.3 now, it should pop up on CurseForge or Modrinth soon

**Comment by java-jambalaya** [comment]
Thanks :)
