### ISSUE TITLE
Compatibility with "Command Block IDE"

### ISSUE THREAD

**Issue by ItsProfessional** [Tectato/BetterCommandBlockUI#20]
[Command Block IDE](https://modrinth.com/mod/command-block-ide)

Perhaps when you double click on a command in Command Block IDE's screen, the "Better Command Block UI" screen should open, and pressing escape should bring you back to the previous screen?

**Comment by Tectato** [comment]
I would need the help of someone who's well versed in mixing into other mods to do that, right now I don't have the capacity to work out something that complex on my own
