### ISSUE TITLE
1.20.2 support

### ISSUE THREAD

**Issue by zax71** [Tectato/BetterCommandBlockUI#21]
Currently, the mod crashes when run on 1.20.2 fabric. See a [log here](https://mclo.gs/yVFEXBo)

## Reproduction
- Install Fabric 1.20.2 (I am using Prism)
- Install [Fabric API](https://modrinth.com/mod/fabric-api) and [Better Command Block UI](https://modrinth.com/mod/bettercommandblockui)
- Launch and see crash stated in attached log

**Comment by Tectato** [comment]
Updated 👍
