### ISSUE TITLE
Question: What is it in options?

### ISSUE THREAD

**Issue by NnicanBuak** [Tectato/BetterCommandBlockUI#24]
#### What is it?
![image](https://github.com/Tectato/BetterCommandBlockUI/assets/89499782/54e50337-3b88-44b7-b2f4-30e0d74efb65)

**Comment by Tectato** [comment]
You can replace the 4 with any number (up to 16 i think), move the slider to a notch, then click the button on the right to get the corresponding fraction of 2*pi put in your clipboard. Intended for quickly pasting in common angles like a quarter turn. Though I'm not entirely happy with how this thing handles so I will likely overhaul it in the next proper update.

**Comment by NnicanBuak** [comment]
Here's a suggestion for a design change then: instead of a copy button, a paste button could be used that would paste the selected value to the current cursor location on the command line. Since this function is not customizable, it could be added as a drop-down menu on the right side of the MultiLineTextField window and toggle its display using the button on the top right. And this menu could then contain all the useful tools.

**Comment by Tectato** [comment]
Oh i sort of forgot about this issue...
The newest version replaces the "copy" button with a text field that shows the output value and which highlights the text within when you click on it for easy copying with CTRL+C. I've also added a compass which visualizes the current rotation and which you can click & drag on to set a more exact rotation value
