### ISSUE TITLE
Lag spike after exiting command block

### ISSUE THREAD

**Issue by JasonHorkles** [Tectato/BetterCommandBlockUI#28]
When exiting command blocks, there's a brief lag spike after a second or two, presumably due to the mod saving its settings.

It might be a good idea to use ModMenu for a static configuration instead of saving each time a command block is exited.

**Comment by Tectato** [comment]
Dang I hadn't considered that file access might introduce lag but yeah that's probably it. I've been meaning to switch to something like ModMenu for a while so I'll try to do that for the next update.

**Comment by JasonHorkles** [comment]
Thank you!!

**Comment by Tectato** [comment]
ModMenu support has been added and the config file is now only saved when closing the game: https://github.com/Tectato/BetterCommandBlockUI/issues/30

**Comment by Tectato** [comment]
Release is out
