### ISSUE TITLE
Command block minecarts?

### ISSUE THREAD

**Issue by pawa2401** [Tectato/BetterCommandBlockUI#3]
Can you add support for command block minecarts? It's really useful for executing multiple commands at once. Also, please add this change to the 1.19.2 version of the mod as currently some of the other mods didn't get updated to .3 yet, and I (as well as probably some other users) still use 1.19.2
thx

**Comment by Tectato** [comment]
Minecart support has been added and is available for 1.18.2, 1.19-1.19.2, and 1.19.3 as soon as the files have been verified on CurseForge or Modrinth
