### ISSUE TITLE
Change character wrapping to word wrapping

### ISSUE THREAD

**Issue by JasonHorkles** [Tectato/BetterCommandBlockUI#33]
Currently, it seems like the mod wraps at the character which can make things look a bit odd in some cases. It would be nice if it followed regular word wrapping instead, where the whole word separated by a space will be sent down to the new line if it doesn't fit on the current one (and if text is too long, then it can wrap at a char).

This could go hand-in-hand with my previous suggestion #32 as well, where it would only create a horizontal scroll bar if a long text doesn't fit regularly (instead of wrapping it at a char)

**Comment by Tectato** [comment]
Sounds good, i'll try and see if i can add that

**Comment by Tectato** [comment]
Implemented in newest release
