### ISSUE TITLE
Missing strings in keybind menu

### ISSUE THREAD

**Issue by JasonHorkles** [Tectato/BetterCommandBlockUI#34]
In the keybind menu, there don't seem to be proper strings for the mod:
![image](https://github.com/Tectato/BetterCommandBlockUI/assets/51760372/ce03a68b-bf5a-42a5-8743-4d10fff18b66)

**Comment by Tectato** [comment]
Oh yeah, forgot about those

**Comment by Tectato** [comment]
Fixed in the new release
