### ISSUE TITLE
[Feature Request/Issue] New Update Control+Backspace Behavior Toggle

### ISSUE THREAD

**Issue by aaryancanvas899** [Tectato/BetterCommandBlockUI#35]
So in the most recent update the ctrl+backspace behavior has been altered. Now the problem is that when editing commands the underscores ( _ ) which are utilized in most item ids with multiple words in them are making it so that the id is not deleted with a single ctrl+backspace. This results in some spamming required to delete large ids like magma_cube_spawn_egg. 

I would like to request a feature to toggle this behavior in the config menu or just a fix which makes ctrl+backspace ignore underscores.
If any existing fixes are possible please let me know.

**Comment by Tectato** [comment]
yeah i hadn't considered that those are often part of strings, i'll make them ignored by default for the full release

**Comment by Tectato** [comment]
Release is out now
