### ISSUE TITLE
[Feature Request] Enter key not leave command UI

### ISSUE THREAD

**Issue by SpyCoder77** [Tectato/BetterCommandBlockUI#37]
I cannot count how many times I have pressed enter to go onto a new line, only to see the gui dissapear. It would act as if I typed a space, and add a line break.

**Comment by Tectato** [comment]
I can add an option to make the gui ignore enter presses altogether, but manual line breaks are not planned

**Comment by Tectato** [comment]
Said option has been added in the latest release
