### ISSUE TITLE
1.19.3 Bug: Button labels not updating to match command block states

### ISSUE THREAD

**Issue by java-jambalaya** [Tectato/BetterCommandBlockUI#4]
Replicated with:
- bettercommandblockui-0.3.1-1.19.3.jar
- fabric-api-0.68.1+1.19.3.jar (fabric 0.14.11)

When changing the command block's state to impulse/chain/repeating, unconditional/conditional, or needs-redstone/always-active, the icon of the button is updated properly when re-opening a command block, but the label/text is not.

Example:
![image](https://user-images.githubusercontent.com/109728217/210772551-046469ac-8733-483f-b206-67cb0bc524ec.png)

This only seems to happen when opening a command block which isn't the default command block state, being impulse, unconditional, and needs redstone, as this is what it always seems to default to.

**Comment by Tectato** [comment]
Issue found, will be fixed in the next release
