### ISSUE TITLE
Feature request: Ability to switch between different command blocks in a chain

### ISSUE THREAD

**Issue by rebrainertv** [Tectato/BetterCommandBlockUI#40]
I would appreciate if it were possible to:
a) save without closing the UI (either with a button, Ctrl+S or both)
b) within the GUI, scroll to the previous/next command block in a chain. 

Something like a previous/next button to save time having to keep track of which command blocks you've clicked on in a very long chain would be extremely useful :)

**Comment by Tectato** [comment]
Very interesting suggestions, I'll look into it!

**Comment by Tectato** [comment]
Added buttons in the latest release to move along the chain (as long as the blocks are within reach, for blocks outside of your reach the server just doesn't send the command block data) and a button to save without leaving the UI
