### ISSUE TITLE
Feature request: custom themes

### ISSUE THREAD

**Issue by Zahar2loshara** [Tectato/BetterCommandBlockUI#43]
What about some customazable themes?
(Idk where say a suggestion)

**Comment by Zahar2loshara** [comment]
In the text field and borders customazable color

**Comment by Tectato** [comment]
well i guess i _could_ add that, but for now i'd like to focus on improving the mod's features. Right now the text field border is hardcoded, but as far as the buttons are concerned, you should be able to modify those using a resource pack
