### ISSUE TITLE
Suggestion: Add names and desc. in "tools"

### ISSUE THREAD

**Issue by Zahar2loshara** [Tectato/BetterCommandBlockUI#46]
I have a question about "Tools" button, what the hell is on in that menu, 2π/(whatever you want) with some sort of compass, and colors, its not doing anything
0.5.2 ver. On 1.20.1

**Comment by Tectato** [comment]
You select an angle and it returns radians, which are used in basically all commands involving rotation. I figured the 2π and compass were enough to imply that angles are involved here.
Similarly you can click on the gradients or put in discrete values in the color section and you get an integer and hex representation of that color, the two most common color formats in commands.
