### ISSUE TITLE
1.19.3 Bug: Syntax suggestions displayed in inconsistent locations

### ISSUE THREAD

**Issue by java-jambalaya** [Tectato/BetterCommandBlockUI#5]
Replicated with:
- bettercommandblockui-0.3.1-1.19.3.jar
- fabric-api-0.68.1+1.19.3.jar (fabric 0.14.11)

Examples:
![image](https://user-images.githubusercontent.com/109728217/210774834-f78f1003-ef39-4831-b3a1-fbf99084dd69.png)
![image](https://user-images.githubusercontent.com/109728217/210774649-1dfc3c08-9af1-4f5a-8476-0bffc3959c88.png)
![image](https://user-images.githubusercontent.com/109728217/210774767-3e82f2e9-eff2-4794-9fa1-aba756e2e6bf.png)

**Comment by Tectato** [comment]
The suggestion window now sticks to the cursor position
