### ISSUE TITLE
1.19.3 Crash when opening a command block

### ISSUE THREAD

**Issue by Ninty9** [Tectato/BetterCommandBlockUI#6]
[crash-2023-02-12_03.00.45-client.txt](https://github.com/Tectato/BetterCommandBlockUI/files/10715112/crash-2023-02-12_03.00.45-client.txt)

**Comment by Tectato** [comment]
The crash log states you're using 1.19.2, while the crash stems from a line of the 1.19.3 version of the mod.
1.19.3 introduced breaking changes to how Minecraft's UI works so the two versions of the mod are not interchangeable.

**Comment by Ninty9** [comment]
Oh, that makes sense, sorry about that, my bad!
