### ISSUE TITLE
1.19.2 Crash when using slider

### ISSUE THREAD

**Issue by Puffadillo** [Tectato/BetterCommandBlockUI#7]
Minecraft 1.19.2
Quilt Loader 0.17.8
Crash report: https://gist.github.com/Puffadillo/58aae26e52dc744d7a6b2ec7d37030fe

Opened a command block, looked through the UIs, and clicked one of the sliders a couple times before the game froze and crashed. No commands were input into the block itself yet.

**Comment by Tectato** [comment]
Sorry for the wait, this should be fixed on the latest version
