### ISSUE TITLE
1.19.4 Support

### ISSUE THREAD

**Issue by ErrorNoInternet** [Tectato/BetterCommandBlockUI#9]

**Comment by Tectato** [comment]
The latest version should already support 1.19.4, and in my testing it did, can you be more specific? Did you encounter a crash with it?

**Comment by ErrorNoInternet** [comment]
Yes, it crashes in 1.19.4: https://mclo.gs/M8Ec03g
It might be caused by other mods though. However, If I remove BetterCommandBlockUI, the game launches normally.

**Comment by Tectato** [comment]
![grafik](https://user-images.githubusercontent.com/70598501/227767448-bfc90fb6-a087-4347-8d05-684268913040.png)
you're using the 1.19.3 version of the mod

**Comment by ErrorNoInternet** [comment]
Oh I didn't see the updated one on CurseForge, sorry about that 😅
I was looking at the one here, which is still at 1.19.3: https://modrinth.com/mod/bettercommandblockui
![image](https://user-images.githubusercontent.com/61157623/227768253-9c100d0a-575b-4f38-a55d-175d7544368d.png)

Thanks for pointing that out

**Comment by Tectato** [comment]
The modrinth page also has the newest release under the 'versions' tab, i dont know why it doesnt show up in the featured list
